### PR TITLE
Fix document titles

### LINKED ISSUE #77: Improve page titles.
We should have better page titles. [Here is how the pattern directory does it.](https://github.com/WordPress/pattern-directory/blob/26b1313fab6d9733d4ff6b6d5e4d89924137715b/public_html/wp-content/themes/pattern-directory/functions.php#L306)

### PR DESCRIPTION
**Pull request by StevenDufresne**
Closes #77.

This PR reimplements some of [document title logic ](https://github.com/WordPress/wordpress.org/blob/a82a685677217f833ef477ffd7bef1590cbc3b83/wordpress.org/public_html/wp-content/themes/pub/wporg-showcase/functions.php#L263)from the original wporg-showcase theme along with some improvements taken from the [plugin theme for paging results](https://github.com/WordPress/wordpress.org/blob/a82a685677217f833ef477ffd7bef1590cbc3b83/wordpress.org/public_html/wp-content/themes/pub/wporg-plugins/functions.php#L276).

| Page | Title |
| --- | --- | 
| Front Page | `The Best WordPress Sites in the World \| WordPress.org` |
| Single | `The Modern House - WordPress Showcase \| WordPress.org` |
| Tag | `Sites tagged as “adventure” \| WordPress.org` |
| Category  | `Sites categorized as “uncategorized” \| WordPress.org` |
| Search | `Search Results for “c” \| WordPress.org` |
| Search Paged  | `Search Results for “c” \| Page 3 of 40 \| WordPress.org` |
| Page  | `Submit a site \| WordPress.org` |

### CODE REVIEW

File: source/wp-content/themes/wporg-showcase-2022/functions.php [hunk 1]
```diff
@@ -257,3 +259,57 @@ function set_site_breadcrumbs( $breadcrumbs ) {
...
+ */
+function document_title( $parts ) {
+	global $wp_query;
+
+	if ( is_front_page() ) {
+		$parts['title']   = $parts['tagline'];
+		$parts['tagline'] = __( 'WordPress.org', 'wporg' );
+	} else {
+		if ( is_single() ) {
+			$parts['title'] = sprintf( esc_attr__( '%s - WordPress Showcase', 'wporg-showcase' ), esc_attr( $parts['title'] ) );
```
Comment (dd32) [inline source/wp-content/themes/wporg-showcase-2022/functions.php:284]: Due to the lack of output in this function, and lack of escaping elsewhere within it, you can safely drop the esc_attr here IMHO.

```suggestion
			$parts['title'] = sprintf( __( '%s - WordPress Showcase', 'wporg-showcase' ), $parts['title'] );
```

**Review by dd32 — APPROVED** [review]
This looks good to me.

There might be smaller tweaks needed later on, but this is resembles the existing code and other sites close enough.

I do question if `"%s"` is needed, if it shouldn't just be `Sites tagged as TagNameHere`, that's more a personal thing, and we probably use `"` elsewhere anyway?
